### ISSUE TITLE
Pull

### ISSUE THREAD

**Issue by suzanasalama** [hedra-editora/kafka_metamorfose_quadradocirculo#1]
@paulopompermaier preciso que você aprove meus pulls no branch atual. E também que revise as pretas do Benjamin e Carpeaux — talvez esteja esquisito mas precisa constar. Por favor me avise quando fizer isso pois preciso pedir pra @jmurachovsky revisar as viúvas

**Comment by jmurachovsky** [comment]
@paulopompermaier @suzanasalama posso revisar as viuvas?

**Comment by suzanasalama** [comment]
@jmurachovsky já falei contigo, mas só pra formalizar por aqui que não é necessário pois essa revisão já foi feita! Obrigada
